//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBaoCaoDanhGia_KHDGN
    {
        public int Id { get; set; }
        public int STT { get; set; }
        public int IdDonVi { get; set; }
        public int IdKeHoachDGN { get; set; }
        public string GioiThieuChung { get; set; }
        public string TomtatQuaTrinh { get; set; }
        public string Tomtat_PhuHop { get; set; }
        public string Tomtat_BaoQuat { get; set; }
        public string Tomtat_ConThieu { get; set; }
        public string Tomtat_NXChung { get; set; }
        public string DiemManh { get; set; }
        public string DiemYeu { get; set; }
        public string DanhGiaTieuChuan { get; set; }
        public string DanhGiaTieuChi { get; set; }
        public string KetLuan { get; set; }
        public string KienNghi { get; set; }
        public Nullable<int> KQDatMuc { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> FInUse { get; set; }
    }
}
