//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDanhGiaTieuChi
    {
        public int Id { get; set; }
        public int STT { get; set; }
        public int IdDonVi { get; set; }
        public int IdKeHoachTDG { get; set; }
        public Nullable<int> IdTieuChi { get; set; }
        public string YeuCauA { get; set; }
        public string GoiYA { get; set; }
        public string MoTaA { get; set; }
        public string MinhChungA { get; set; }
        public Nullable<bool> KQDatA { get; set; }
        public string YeuCauB { get; set; }
        public string GoiYB { get; set; }
        public string MoTaB { get; set; }
        public string MinhChungB { get; set; }
        public Nullable<bool> KQDatB { get; set; }
        public string YeuCauC { get; set; }
        public string GoiYC { get; set; }
        public string MoTaC { get; set; }
        public string MinhChungC { get; set; }
        public Nullable<bool> KQDatC { get; set; }
        public string DiemManh { get; set; }
        public string DiemYeu { get; set; }
        public string YKienLanhDao { get; set; }
        public string YKienCapTrenDG { get; set; }
        public Nullable<int> KQDatMuc { get; set; }
        public Nullable<bool> CapTrenDuyet { get; set; }
        public string KeHoachCaiTien { get; set; }
        public string YKienCapTrenKHCT { get; set; }
        public string Nhom { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> FInUse { get; set; }
    }
}
