//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDanhGiaTieuChiMuc4_KHDGN
    {
        public int Id { get; set; }
        public Nullable<int> STT { get; set; }
        public int IdDonVi { get; set; }
        public int IdKeHoachDGN { get; set; }
        public Nullable<int> IdTieuChuan { get; set; }
        public Nullable<int> IdTieuChi { get; set; }
        public string DiemManh { get; set; }
        public string DiemYeu { get; set; }
        public string KeHoachCaiTien { get; set; }
        public string NoiDungBoSung { get; set; }
        public string DanhGia { get; set; }
        public string Nhom { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> FInUse { get; set; }
    }
}
