//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKeHoachTDG
    {
        public int Id { get; set; }
        public int STT { get; set; }
        public int IdDonVi { get; set; }
        public Nullable<int> IdQuyDinhTC { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public int NamHocBD { get; set; }
        public int NamHocKT { get; set; }
        public string NoiDung { get; set; }
        public string TrangThai { get; set; }
        public string MucDich { get; set; }
        public string PhamVi { get; set; }
        public string CongCu { get; set; }
        public string TapHuanNghiepVu { get; set; }
        public string NguonLuc { get; set; }
        public string ThueChuyenGia { get; set; }
        public string BangDanhMuc { get; set; }
        public string ThoiGianHoatDong { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> FInUse { get; set; }
    }
}
