//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKeHoachDGN
    {
        public int Id { get; set; }
        public int STT { get; set; }
        public int IdDonVi { get; set; }
        public int Nam { get; set; }
        public string MucDich { get; set; }
        public string NoiDung { get; set; }
        public string NghienCuuHSDG { get; set; }
        public string KhaoSatSoBo { get; set; }
        public string KhaoSatChinhThuc { get; set; }
        public string DuThaoBaoCao { get; set; }
        public string LayYKienPhanHoi { get; set; }
        public string HoanThienBaoCao { get; set; }
        public string ToChucThucHien { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> FInUse { get; set; }
    }
}
