//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKQNghienCuuTieuChiDGN
    {
        public int Id { get; set; }
        public int STT { get; set; }
        public int IdDonVi { get; set; }
        public int IdKeHoachDGN { get; set; }
        public int IdTieuChi { get; set; }
        public Nullable<bool> ChuaDG { get; set; }
        public Nullable<bool> ChuaDGDung { get; set; }
        public Nullable<bool> ChuaDGDayDu { get; set; }
        public string MCKiemTra { get; set; }
        public string MCBoSung { get; set; }
        public string DoiTuongPV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string NoiDungPV { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> FInUse { get; set; }
    }
}
